#%RAML 1.0
---
title: Hello World
version: 1.0

protocols: [ HTTPS ]
baseUri: https://helloworld.service.hmrc.gov.uk/

/test:
  /hello:
    get:
      displayName: Say Hello
      description: |
        A simple hello api
      queryParameters:
        name:
          description: The name to greet
          type: string
          example: Bob
          required: true

