#%RAML 1.0

title: Employers PAYE Service
version: 1.0
baseUri: http://employers-paye.service
mediaType: application/json

/{empRef}:
  /{taxYear}:
    /charges:
  /{other_thing}:
    /humph:
/docs:
  /to_read:
    /now:
      /favorites:
      /backburner:
    /later:
      /important:
      /meh:
  /archive:
    /2014:
    /2015:
