#%RAML 1.0

title: Employers PAYE Service
version: 1.0
baseUri: http://employers-paye.service
mediaType: application/json

/{empRef}:
  get:
    responses:
      200:
        body:
          application/json:
            type: !include schemas/taxyear-schema.json

  /{taxYear}:
    get:
      responses:
        200:
          body:
            application/json:
              type: !include schemas/services-schema.json

    /charges:
      get:
        responses:
          200:
            body:
              application/json:
                type: !include schemas/charges-schema.json
