#%RAML 1.0 Library

usage: Just include it in a "uses" section
types:
    utr:
      type: string
    #    displayName: The Self Assessment UTR of the customer
    #    description: See https://www.tax.service.gov.uk/information/help?helpcategory=security&helpid=UniqueTaxpayReference
    #    default: "2234567890"
    #    required: true
    taxYear:
      type: string
    #    displayName: The tax year the data applies to
    #    default: "2016-17"
    #    required: true
#  vim: set ts=2 sw=2 tw=0 et :
