#%RAML 1.0 ResourceType

displayName: <<displayName>>
get:
  description: <<description>>
  responses:
    200:
      description: <<response-desc>>
      body:
        application/json:
          example: <<response-example>>
