#%RAML 1.0 ResourceType

resourceTypes:
  navigation:
    displayName: <<displayName>>
    get:
      description: <<description>>
      responses:
        200:
          description: <<response-desc>>
          body:
            application/json:
              example: <<response-example>>
#  collection:
#    displayName: <<enclosingResource>>'s <<resourcePathName | !singularize>>
#    get:
#      description: Retrieve the <<enclosingResource>>'s <<resourcePathName>>
#      headers:
#        Accept:
#          description: The content type of the response
#          type: string
#          required: false
#          example: application/vnd.hmrc.1.0+json
#      responses:
#        200:
#          description: the <<enclosingResource>>'s <<resourcePathName>>
#          body:
#            application/json:
#              example: <<GET-example>>
#        400:
#          description: one or more of the identifier(s) in the URL is invalid
#        404:
#          description: no <<resourcePathName>> found for the given identifier(s)
#    post?:
#      description: Add a <<resourcePathName | !singularize>>
#      body:
#        application/json:
#          example: <<POST-example>>
#      headers:
#        Accept:
#          description: The content type of the response
#          type: string
#          required: false
#          example: application/vnd.hmrc.1.0+json
#      responses:
#        201:
#          description: The <<resourcePathName | !singularize>> has been added
#          headers:
#            Location:
#              description: The new <<resourcePathName | !singularize>>'s URL
#              type: string
#              required: true
#        400:
#          description: the <<resourcePathName | !singularize>>'s representation format is invalid
#        403:
#          description: the <<resourcePathName | !singularize>> hasn't been created
#
#  member:
#    get:
#      description: Retrieve the <<resourcePathName | !singularize>>
#      responses:
#        200:
#          body:
#            application/json:
#              example: <<response-sample>>
#        400:
#          description: one or more of the identifier(s) in the URL is invalid
#          body:
#            schema: <<error-schema>>
#        401:
#          description: The provided Credentials are invalid
#          body:
#            schema: <<error-schema>>
#        403:
#          description: The User doesn't have access to this information
#          body:
#            schema: <<error-schema>>
#            example: <<error-sample>>
#        404:
#          description: no <<resourcePathName | !singularize>> found for the given identifier(s)
#          body:
#            schema: <<error-schema>>
#    put:
#      description: Update the <<resourcePathName | !singularize>>
#      body:
#        example: <<request-sample>>
#        headers:
#          Content-Type:
#            description: The content type of the request
#        type: string
#        required: false
#        enum: [ application/vnd.hmrc.1.0+json ]
#      responses:
#        204:
#          description: The <<resourcePathName>> has been updated
#          headers:
#            Location:
#              description: The updated <<resourcePathName | !singularize>>'s URL
#              type: string
#              required: true
#        400:
#          description: the request format is invalid
#          body:
#            schema: <<error-schema>>
#        401:
#          description: The provided Credentials are invalid
#          body:
#            schema: <<error-schema>>
#        403:
#          description: The User doesn't have the right to create a <<resourcePathName | !singularize>>
#          body:
#            schema: <<error-schema>>
#            example: <<error-sample>>
#        404:
#          description: no <<resourcePathName | !singularize>> found for the given identifier(s)
#          body:
#            schema: <<error-schema>>
#    delete:
#      description: Delete the <<resourcePathName | !singularize>>
#      responses:
#        204:
#          description: The <<resourcePathName | !singularize>> has been deleted
#
#
#  vim: set ts=2 sw=2 tw=0 et :
